services:
  robin_neo4j_etl:
    build:
      context: ./robin_neo4j_etl
    env_file:
      - .env
    volumes:
      - ./data/cochrane:/data/cochrane
  robin_evaluation:
    build:
      context: ./robin_evaluation
    env_file:
      - .env
    volumes:
      - ./data/evaluation:/data/evaluation
      - ./data/output:/data/output
      - D:\biomedical-datasets\pmc-collection\raw\retrieved:/data/pmc
      - ./robin_evaluation/src:/app/
    external_links:
      - chatbot_api
  chatbot_api:
    build:
      context: ./chatbot_api
    env_file:
      - .env
    volumes:
      - ./chatbot_api/src/:/app/
      - ./chroma_data:/chroma_data
      - ./chat_histories:/chat_histories
      - ./data/models/:/models/
    depends_on:
      - robin_neo4j_etl
    ports:
      - "8000:8000"

  chatbot_frontend:
    build:
      context: ./chatbot_frontend
    env_file:
      - .env
    volumes:
      - ./chatbot_frontend/src/:/app/
    depends_on:
      - chatbot_api
    ports:
      - "8501:8501"