services:
  robin_neo4j_etl:
    build:
      context: ./robin_neo4j_etl
    env_file:
      - .env
    volumes:
      - ./data/cochrane:/data/cochrane

  chatbot_api:
    build:
      context: ./chatbot_api
    env_file:
      - .env
    depends_on:
      - robin_neo4j_etl
    ports:
      - "8000:8000"

  chatbot_frontend:
    build:
      context: ./chatbot_frontend
    env_file:
      - .env
    depends_on:
      - chatbot_api
    ports:
      - "8501:8501"